Repository devblogs-ir/Twitter.Clone, pull requests merged in 2024-02, with the labels that each got.

#8 Trends init project setup
  Twitter.Clone.sln
  src/services/trends/Twitter.Clone.Trends/Program.cs
  src/services/trends/Twitter.Clone.Trends/Properties/launchSettings.json
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.csproj
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.http
  src/services/trends/Twitter.Clone.Trends/appsettings.Development.json
  src/services/trends/Twitter.Clone.Trends/appsettings.json
  src/shared/Twitter.Clone.Signatures/Class1.cs
  src/shared/Twitter.Clone.Signatures/Twitter.Clone.Signatures.csproj
Labels: review

#9 Stg/trends
  Twitter.Clone.sln
  src/services/trends/Twitter.Clone.Trends/Program.cs
  src/services/trends/Twitter.Clone.Trends/Properties/launchSettings.json
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.csproj
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.http
  src/services/trends/Twitter.Clone.Trends/appsettings.Development.json
  src/services/trends/Twitter.Clone.Trends/appsettings.json
  src/shared/Twitter.Clone.Signatures/Class1.cs
  src/shared/Twitter.Clone.Signatures/Twitter.Clone.Signatures.csproj
Labels: review

#6 init RelationshipService project
  src/services/relationship/Twitter.Clone.Relationship/.editorconfig
  src/services/relationship/Twitter.Clone.Relationship/Controllers/WeatherForecastController.cs
  src/services/relationship/Twitter.Clone.Relationship/Program.cs
  src/services/relationship/Twitter.Clone.Relationship/Properties/launchSettings.json
  src/services/relationship/Twitter.Clone.Relationship/Twitter.Clone.Relationship.APIs.csproj
  src/services/relationship/Twitter.Clone.Relationship/Twitter.Clone.Relationship.APIs.http
  src/services/relationship/Twitter.Clone.Relationship/Twitter.Clone.Relationship.sln
  src/services/relationship/Twitter.Clone.Relationship/WeatherForecast.cs
  src/services/relationship/Twitter.Clone.Relationship/appsettings.Development.json
  src/services/relationship/Twitter.Clone.Relationship/appsettings.json
Labels: review

#12 init - Create VSA setup/folders
  src/services/relationship/.editorconfig
  src/services/relationship/Twitter.Clone.Relationship.API/Controllers/WeatherForecastController.cs
  src/services/relationship/Twitter.Clone.Relationship.API/Program.cs
  src/services/relationship/Twitter.Clone.Relationship.API/Properties/launchSettings.json
  src/services/relationship/Twitter.Clone.Relationship.API/Twitter.Clone.Relationship.API.csproj
  src/services/relationship/Twitter.Clone.Relationship.API/Twitter.Clone.Relationship.APIs.http
  src/services/relationship/Twitter.Clone.Relationship.API/WeatherForecast.cs
  src/services/relationship/Twitter.Clone.Relationship.API/appsettings.Development.json
  src/services/relationship/Twitter.Clone.Relationship.API/appsettings.json
  src/services/relationship/Twitter.Clone.Relationship.Database/Twitter.Clone.Relationship.Database.csproj
  src/services/relationship/Twitter.Clone.Relationship.Entities/Twitter.Clone.Relationship.Entities.csproj
  src/services/relationship/Twitter.Clone.Relationship.Features/Twitter.Clone.Relationship.Features.csproj
  src/services/relationship/Twitter.Clone.Relationship.sln
  src/services/relationship/Twitter.Clone.Relationship/Twitter.Clone.Relationship.sln
Labels: review

#33 Identity provider init project setup
  Twitter.Clone.sln
  src/services/identity-provider/Twitter.Clone.IdentityProvider.Presentation/Controllers/BaseController.cs
  src/services/identity-provider/Twitter.Clone.IdentityProvider.Presentation/DependencyInjection.cs
  src/services/identity-provider/Twitter.Clone.IdentityProvider.Presentation/Program.cs
  src/services/identity-provider/Twitter.Clone.IdentityProvider.Presentation/Properties/launchSettings.json
  src/services/identity-provider/Twitter.Clone.IdentityProvider.Presentation/Twitter.Clone.IdentityProvider.Presentation.csproj
  src/services/identity-provider/Twitter.Clone.IdentityProvider.Presentation/Twitter.Clone.IdentityProvider.Presentation.http
  src/services/identity-provider/Twitter.Clone.IdentityProvider.Presentation/appsettings.Development.json
  src/services/identity-provider/Twitter.Clone.IdentityProvider.Presentation/appsettings.json
  src/services/identity-provider/Twitter.Clone.IdentityPrvider.Application/DependencyInjection.cs
  src/services/identity-provider/Twitter.Clone.IdentityPrvider.Application/Twitter.Clone.IdentityPrvider.Application.csproj
  src/services/identity-provider/Twitter.Clone.IdentityPrvider.Domain/Twitter.Clone.IdentityPrvider.Domain.csproj
  src/services/identity-provider/Twitter.Clone.IdentityPrvider.Infrastructure/DependencyInjection.cs
  src/services/identity-provider/Twitter.Clone.IdentityPrvider.Infrastructure/IdentityContext.cs
  src/services/identity-provider/Twitter.Clone.IdentityPrvider.Infrastructure/Twitter.Clone.IdentityPrvider.Infrastructure.csproj
  src/services/trends/Twitter.Clone.Trends/Program.cs
  src/services/trends/Twitter.Clone.Trends/Properties/launchSettings.json
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.csproj
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.http
  src/services/trends/Twitter.Clone.Trends/appsettings.Development.json
  src/services/trends/Twitter.Clone.Trends/appsettings.json
  src/shared/Twitter.Clone.Signatures/Class1.cs
  src/shared/Twitter.Clone.Signatures/Twitter.Clone.Signatures.csproj
  trend.service.slnf
Labels: review, ready to merge, feature

#34 Messenger documentation for show my messages
  documents/UserStories/ShowMyMessages.Md
Labels: feature, documentation

#42 Add documentation for direct message service
  documents/UserStories/DirectMessageService.md
Labels: documentation

#119 Search engine init project setup
  src/services/search-engine/Twitter.Clone.Search.Application/ConfigureServices.cs
  src/services/search-engine/Twitter.Clone.Search.Application/Twitter.Clone.Search.Application.csproj
  src/services/search-engine/Twitter.Clone.Search.Domain/Twitter.Clone.Search.Domain.csproj
  src/services/search-engine/Twitter.Clone.Search.Infrastracture/ApplicationDbContext.cs
  src/services/search-engine/Twitter.Clone.Search.Infrastracture/ConfigureServices.cs
  src/services/search-engine/Twitter.Clone.Search.Infrastracture/Twitter.Clone.Search.Infrastracture.csproj
  src/services/search-engine/Twitter.Clone.Search.Presentation/ConfigureServices.cs
  src/services/search-engine/Twitter.Clone.Search.Presentation/Program.cs
  src/services/search-engine/Twitter.Clone.Search.Presentation/Properties/launchSettings.json
  src/services/search-engine/Twitter.Clone.Search.Presentation/Twitter.Clone.Search.Presentation.csproj
  src/services/search-engine/Twitter.Clone.Search.Presentation/Twitter.Clone.Search.Presentation.http
  src/services/search-engine/Twitter.Clone.Search.Presentation/appsettings.Development.json
  src/services/search-engine/Twitter.Clone.Search.Presentation/appsettings.json
  src/services/search-engine/Twitter.Clone.Search.sln
Labels: ready

#121 Settings init project setup
  src/services/settings/.editorconfig
  src/services/settings/Domain
  src/services/settings/README.md
  src/services/settings/Twitter.Clone.Settings.Business/Class1.cs
  src/services/settings/Twitter.Clone.Settings.Business/Twitter.Clone.Settings.Business.csproj
  src/services/settings/Twitter.Clone.Settings.Domain/Entities/BlockedListSetting.cs
  src/services/settings/Twitter.Clone.Settings.Domain/Entities/NotificationSetting.cs
  src/services/settings/Twitter.Clone.Settings.Domain/Twitter.Clone.Settings.Domain.csproj
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/BlockedPageConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/BlockedUserConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/EmailNotificationConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/IEntityTypeConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/SmsNotificationConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Context/IEntityConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Context/SettingsDbContext.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/GlobalUsing.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Twitter.Clone.Settings.Infrastructure.Persistence.csproj
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Controllers/WeatherForecastController.cs
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Program.cs
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Properties/launchSettings.json
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Twitter.Clone.Settings.NotificationSetting.http
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Twitter.Clone.Settings.csproj
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/appsettings.Development.json
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/appsettings.json
  src/services/settings/Twitter.Clone.Settings.sln
  src/services/settings/Twitter.Clone.Settings/Entities/BlockedListSetting.cs
  src/services/settings/Twitter.Clone.Settings/Entities/NotificationSetting.cs
  src/services/settings/Twitter.Clone.Settings/Program.cs
  src/services/settings/Twitter.Clone.Settings/Properties/launchSettings.json
  src/services/settings/Twitter.Clone.Settings/Twitter.Clone.Settings.csproj
  src/services/settings/Twitter.Clone.Settings/Twitter.Clone.Settings.http
  src/services/settings/Twitter.Clone.Settings/appsettings.Development.json
  src/services/settings/Twitter.Clone.Settings/appsettings.json
  src/services/settings/image.png
Labels: change, init

#122 Settings init project setup
  src/services/settings/Twitter.Clone.Settings.Business/Class1.cs
  src/services/settings/Twitter.Clone.Settings.Business/Twitter.Clone.Settings.Business.csproj
  src/services/settings/Twitter.Clone.Settings.Domain/Entities/BlockedListSetting.cs
  src/services/settings/Twitter.Clone.Settings.Domain/Entities/NotificationSetting.cs
  src/services/settings/Twitter.Clone.Settings.Domain/Twitter.Clone.Settings.Domain.csproj
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/BlockedPageConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/BlockedUserConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/EmailNotificationConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/IEntityTypeConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Cofiguration/SmsNotificationConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Context/IEntityConfiguration.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Context/SettingsDbContext.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/GlobalUsing.cs
  src/services/settings/Twitter.Clone.Settings.Infrastructure.Persistence/Twitter.Clone.Settings.Infrastructure.Persistence.csproj
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Controllers/WeatherForecastController.cs
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Program.cs
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Properties/launchSettings.json
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Twitter.Clone.Settings.NotificationSetting.http
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/Twitter.Clone.Settings.csproj
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/appsettings.Development.json
  src/services/settings/Twitter.Clone.Settings.NotificationSetting/appsettings.json
Labels: change

#124 Stg/settings
  src/services/settings/Twitter.Clone.Settings/Business/UserNotificationResponse.cs
  src/services/settings/Twitter.Clone.Settings/Context/SettingsDbContext.cs
  src/services/settings/Twitter.Clone.Settings/Entities/NotificationSetting.cs
  src/services/settings/Twitter.Clone.Settings/Protos/notification.proto
  src/services/settings/Twitter.Clone.Settings/Services/NotificationService.cs
  src/services/settings/Twitter.Clone.Settings/Twitter.Clone.Settings.csproj
Labels: review

#156 Trends init project setup
  Twitter.Clone.sln
  src/services/trends/Twitter.Clone.Trends/Program.cs
  src/services/trends/Twitter.Clone.Trends/Properties/launchSettings.json
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.csproj
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.http
  src/services/trends/Twitter.Clone.Trends/appsettings.Development.json
  src/services/trends/Twitter.Clone.Trends/appsettings.Production.json
  src/services/trends/Twitter.Clone.Trends/appsettings.json
  twitter.clone.trends.slnf
Labels: review, init

#159 Stg/trends merge to main
  Twitter.Clone.sln
  src/services/trends/Twitter.Clone.Trends/Program.cs
  src/services/trends/Twitter.Clone.Trends/Properties/launchSettings.json
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.csproj
  src/services/trends/Twitter.Clone.Trends/Twitter.Clone.Trends.http
  src/services/trends/Twitter.Clone.Trends/appsettings.Development.json
  src/services/trends/Twitter.Clone.Trends/appsettings.Production.json
  src/services/trends/Twitter.Clone.Trends/appsettings.json
  twitter.clone.trends.slnf
Labels: feat

#162 Locator init project setup
  Twitter.Clone.sln
  src/services/locator/Twitter.Clone.Locator/Program.cs
  src/services/locator/Twitter.Clone.Locator/Properties/launchSettings.json
  src/services/locator/Twitter.Clone.Locator/Twitter.Clone.Locator.csproj
  src/services/locator/Twitter.Clone.Locator/Twitter.Clone.Locator.http
  src/services/locator/Twitter.Clone.Locator/appsettings.Development.json
  src/services/locator/Twitter.Clone.Locator/appsettings.json
  twitter.clone.locator.slnf
Labels: feat

#163 Locator get location of by user ip
  src/services/locator/Twitter.Clone.Locator/Extensions/ServiceCollectionExtensions.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/Domain/Location.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/GeoLocationResponse.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/GeoLocatorApi.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/GeoLocatorDatabase.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/IGeoLocator.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/LocationFinder.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/LocationResponse.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/LocationServiceAppSettings.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/UnableToConnectLocatorApiException.cs
  src/services/locator/Twitter.Clone.Locator/GlobalUsings.cs
  src/services/locator/Twitter.Clone.Locator/Persistence/LocatorDbContext.cs
  src/services/locator/Twitter.Clone.Locator/Persistence/Migrations/20240222164139_InitialDbContext.Designer.cs
  src/services/locator/Twitter.Clone.Locator/Persistence/Migrations/20240222164139_InitialDbContext.cs
  src/services/locator/Twitter.Clone.Locator/Persistence/Migrations/LocatorDbContextModelSnapshot.cs
  src/services/locator/Twitter.Clone.Locator/Program.cs
  src/services/locator/Twitter.Clone.Locator/Twitter.Clone.Locator.csproj
  src/services/locator/Twitter.Clone.Locator/Twitter.Clone.Locator.http
  src/services/locator/Twitter.Clone.Locator/appsettings.Development.json
Labels: ready, feat

#164 Stg/locator
  Twitter.Clone.sln
  src/services/locator/Twitter.Clone.Locator/Extensions/ServiceCollectionExtensions.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/Domain/Location.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/GeoLocationResponse.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/GeoLocatorApi.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/GeoLocatorDatabase.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/IGeoLocator.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/LocationFinder.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/LocationResponse.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/LocationServiceAppSettings.cs
  src/services/locator/Twitter.Clone.Locator/Features/LocationService/UnableToConnectLocatorApiException.cs
  src/services/locator/Twitter.Clone.Locator/GlobalUsings.cs
  src/services/locator/Twitter.Clone.Locator/Persistence/LocatorDbContext.cs
  src/services/locator/Twitter.Clone.Locator/Persistence/Migrations/20240222164139_InitialDbContext.Designer.cs
  src/services/locator/Twitter.Clone.Locator/Persistence/Migrations/20240222164139_InitialDbContext.cs
  src/services/locator/Twitter.Clone.Locator/Persistence/Migrations/LocatorDbContextModelSnapshot.cs
  src/services/locator/Twitter.Clone.Locator/Program.cs
  src/services/locator/Twitter.Clone.Locator/Properties/launchSettings.json
  src/services/locator/Twitter.Clone.Locator/Twitter.Clone.Locator.csproj
  src/services/locator/Twitter.Clone.Locator/Twitter.Clone.Locator.http
  src/services/locator/Twitter.Clone.Locator/appsettings.Development.json
  src/services/locator/Twitter.Clone.Locator/appsettings.json
  twitter.clone.locator.slnf
Labels: ready, feat

#165 Add locator contract project
  Twitter.Clone.sln
  src/services/locator/Twitter.Clone.Locator.Contracts/LocationResponse.cs
  src/services/locator/Twitter.Clone.Locator.Contracts/Twitter.Clone.Locator.Contracts.csproj
  src/services/locator/Twitter.Clone.Locator/GlobalUsings.cs
  src/services/locator/Twitter.Clone.Locator/Twitter.Clone.Locator.csproj
  twitter.clone.locator.slnf
Labels: fix

#155 Messenger init project setup
  Twitter.Clone.sln
  src/services/messenger/Twitter.Clone.Messenger/Program.cs
  src/services/messenger/Twitter.Clone.Messenger/Properties/launchSettings.json
  src/services/messenger/Twitter.Clone.Messenger/Twitter.Clone.Messenger.csproj
  src/services/messenger/Twitter.Clone.Messenger/Twitter.Clone.Messenger.http
  src/services/messenger/Twitter.Clone.Messenger/appsettings.Development.json
  src/services/messenger/Twitter.Clone.Messenger/appsettings.json
  twitter.clone.messenger.slnf
Labels: ready, init

#149 Init media project setup
  Twitter.Clone.sln
  src/services/media/Twitter.Clone.Media.Api/Program.cs
  src/services/media/Twitter.Clone.Media.Api/Properties/launchSettings.json
  src/services/media/Twitter.Clone.Media.Api/Twitter.Clone.Media.Api.csproj
  src/services/media/Twitter.Clone.Media.Api/Twitter.Clone.Media.Api.http
  src/services/media/Twitter.Clone.Media.Api/appsettings.Development.json
  src/services/media/Twitter.Clone.Media.Api/appsettings.json
  src/services/media/Twitter.Clone.Media.Application/Twitter.Clone.Media.Application.csproj
  src/services/media/Twitter.Clone.Media.Domain/Twitter.Clone.Media.Domain.csproj
  src/services/media/Twitter.Clone.Media.Infrastructure/Twitter.Clone.Media.Infrastructure.csproj
  src/shared/Twitter.Clone.Signatures/Class1.cs
Labels: change, init

#182 Tweet publish composed tweet message
  src/services/tweet/Core/Twitter.Clone.Tweet.Application/Tweet/Command/CreateTweet/CreateTweetCommandHandler.cs
  src/services/tweet/Infrastructure/Twitter.Clone.Tweet.Infrastructure/AppSettings.cs
  src/services/tweet/Infrastructure/Twitter.Clone.Tweet.Infrastructure/Models/MongoDbConfigurationModel.cs
  src/services/tweet/Infrastructure/Twitter.Clone.Tweet.Infrastructure/Repository/TweetRepository.cs
  src/services/tweet/Presentation/Twitter.Clone.Tweet.WebApi/PresentationConfigureServices.cs
  src/services/tweet/Presentation/Twitter.Clone.Tweet.WebApi/appsettings.json
  src/shared/Twitter.Clone.MessagingContracts/Tweet/NakedComposedTweetMessage.cs
Labels: feat
